# Generated by Django 5.0.14 on 2026-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Science', 'Science'), ('Mathematics', 'Mathematics'), ('General Knowledge', 'General Knowledge'), ('Aptitude', 'Aptitude'), ('History', 'History'), ('Literature', 'Literature'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
